sql.md

I removed the explicit references to Python as they are confusing and irrelevant.
I also added the lesson layout (so that the lessons are displayed like http://apawlik.github.io/sql-ecology/). The reason why the lesson layout is not showing in commits is probably because I created this PR previously, merged myself (in a rush to have things ready for Utrecht) and then reverted the merge - as @hlapp righteously pointed out that someone else should review and merge. Summarizing, the main changes are the Python references and the lesson layout.
I think even if the lesson template changes, it's worth to get most of our lessons in a lesson template so that they render nicely. They can be updated if needed with new template in the future.

Rephrased references to Python & added lesson layout

---

sql.md

The SQL standard requires single-quotes (apostrophes) for strings;
double-quoted strings denote quoted identifiers which are matched case
sensitively on most engines.
Double quoted strings work on *some* engines (specifically SQLite and
MySQL with its default settings - possibly Access although I'm not
familiar with it) but on most other engines (DB2, Oracle, Firebird,
later versions of PostgreSQL, etc.) they will fail. Single quoted
strings work universally, so this won't break any existing lessons but
may save learners some headaches in future!

Use single-quotes for strings

---

01-sql-basic-queries.md
sql-solutions.md

Re-applying changes for strings now the lessons have been split into
separate files. Also fixed a few cases in the sql-solutions page where
numbers were quoted as strings but obviously being treated as numbers
(for example, weight > "75").

Use single quotes for strings

---

sql-solutions.md

Fairly major tidy up of SQL solutions: removed all trailing whitespace,
wrapped everything at 80 columns and made all indentation consistent (as
per CONTRIBUTING.md). Also fixed several errors in the queries: many
referred to columns like "species", "plot" and "wgt", but these are
"species_id", "plot_id", and "weight" in database. Some queries
intending to convert g to kg divided by 100 instead of 1000, and there
were plenty of extraneous brackets to remove.

Tidy up SQL solutions

---

00-sql-introduction.md

If this option is checked when importing `surveys.csv` into *SQLite Manager* then empty entries in the (right-most) `weight` column are not recognised as nulls and instead appear to be treated as zeros: arithmetic on `weight` results in zeros where one would expect to see nulls.
Horrible problem to debug in a workshop so added note to `00-sql-introduction.md` asking that students ensure that *Ignore trailing Separator/Delimiter* be left unchecked.

Ask that 'Ignore trailing Separator/Delimiter' be left unchecked

---

02-sql-aggregation.md

Previously, some of the query examples weren't displaying as a code block, because the Markdown text was not indented enough. This commit fixes that (four spaces of indentation will cause the SELECT statements to display as a code block).
Fixes #105.

Fix code block formatting in "Null values" section

---

03-sql-joins-aliases.md

Proposed changes in response to issue #110. 
Builds on the existing `JOIN` query example to make a distinction between `INNER JOIN` and `LEFT OUTER JOIN`.
To minimize the amount of new material I've made no mention of join types that are not relevant to SQLite. I've also made no mention of the difference between primary/foreign keys.

added discussion of inner and left outer joins to 03-sql-joins-aliases.md

---

_episodes/00-sql-introduction.md
setup.md

This modifies the setup and intro slightly to clarify that SQL manager is used
throughout and is more explicit about the location of the first file used
(typical point of confusion).
Related to #133

Clarify flow and narrative of 00-sql-intro

---

_episodes/03-sql-joins-aliases.md

In lesson 03-sql-joins-aliases, the example using IFNULL for species_id adds the IFNULL function to the wrong table. The species table does not contain any NULL species_id values, but the surveys table does.

IFNULL on wrong table

---

_episodes/02-sql-aggregation.md

Fixed the first query from the saved view in the 02-sql-aggregation lesson. In the text, it states "There should only be six records", which is only true with a filter on species_id (as is true for the subsequent queries that build on this one).

add filter to view query

---

setup.md

included info on downloading the ESR version and how long we expect it to be supported. This is just the short-fix for this problem. Eventually the setup information will need to be modified to include instructions on how to use something other than SQLite Manager.

added information about issues with Firefox 57

---

_episodes/00-sql-introduction.md
index.md
reference.md
setup.md

this fixes the issue mentioned in [this comment](https://github.com/datacarpentry/sql-ecology-lesson/issues/229#issuecomment-400636025). Before merging, it would be good to check that links within the lessons pointing to `/setup/` and `/reference/` are updated.
This is a consequence of this change: https://github.com/carpentries/lesson-example/pull/127

remove permalinks

---

_episodes/00-sql-introduction.md

Hi, I've made some modifications to the Import instructions list as part of the lesson "Databases using SQL". The only modifcations were in 00-sql-introduction.md.
These changes make the instructions clearer and correct numerous typos and various inconsistencies, to better reflect a learner following the steps.
An overview of the specific changes:
(Step numbered refers to the pre-modifed version):
- Menu selection steps had a mix of separators:  `>>`, `->`, `>`. Changed to just be `>>`.
- Removed the line `Choose Start the import **Database -> Import**`
- Changed the list numbering as appropriate (although we could use lazy list numbering and  Markdown will correctly order for us).
- Split line 4 into two instructions
- For step 7: “test some of the options and until the preview”: removed …

Numerous corrections to the Import subsection of 00-sql-introduction.md

---

_episodes/02-sql-aggregation.md

Line 9: group -> grouped
Line 38: to 1000.0 -> by 1000.00 (to match what’s done in the following script)
Line 69: clause -> clause.
Line 192: requires to -> requires us to
Line 193: my project -> our project (to match the voice of the rest of the episode and lessons)
Lines 216, 226, 233, 242: species_id == ‘PE’ -> species_id = ‘PE’ (nowhere else in the lessons uses a double-equal sign)

Several minor grammar and consistency change suggestions

---

_episodes/03-sql-joins.md

I notice that the challenge solutions at end of the [*Joins* lesson](http://www.datacarpentry.org/sql-ecology-lesson/03-sql-joins/) were not being numbered correctly: each solution was numbered "1.". This pull request fixes that by reindenting the source code blocks, and works correctly when I run `make serve` on my computer.

Reindented solutions so list items increment correctly

---

_episodes/01-sql-basic-queries.md

Following the examples in the rest of the lesson that proceed by limiting data rather than selecting more data, I think the first example should be the wildcard rather than "year".

Change order of first three queries

---

_episodes/00-sql-introduction.md

This edit to the "What is SQL?" section of episode 00 adds "select" to the types of database operations afforded by SQL, per @SebastianMosidi 's suggestion.

add 'select' to list of SQL query types (fixes #301)

---

_episodes/03-sql-joins.md

`COALESCE` is part of the SQL standard, while `IFNULL` is specific to SQLite.

Replace `IFNULL` with `COALESCE`

---

setup.md

Suggest an option for most Windows users. Also removes the link to SQLite, which can create confusion whether both need to be installed separately. Also added a sentence to make clear that SQLite is included with DB Browser for SQLite.

Expand download and install instructions for DB Browser

---

episodes/00-sql-introduction.md
episodes/01-sql-basic-queries.md
learners/discuss.md
learners/setup.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
- Closes #370
- Closes #372
- Closes #374
- Closes #375
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Clarifies installation, instructions for opening a database file, and SELECT behavior and fixes list formatting in a proposed lesson.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are …

Text clarifications and minor formatting fixes
