sql_cheat_sheet.md
This cheat sheet was original authored by Ethan White (@ethanwhite)
and Karen Cranston (@kcranston).
=> Add cheat sheet that was lost in the repository split

sql.md
Something students have noted in the past is that there is a lot going on in the SQLite Manager
interface and that without a walk through this can be confusing. This addresses that by helping
remind the instructor to give them a brief tour.
=> Add section introducing the SQLite Manager interface

sql.md
Update the setup instructions to work with newer versions of Firefox.
=> Update setup instructions

sql.md
1. Change the download url
2. Change column names where necessary
=> Switch data source to Portal Project Teaching Database

CONTRIBUTING.md, CONTRIBUTORS.md, README.md
=> Update the documentation files to reflect move to single repository

sql.md
Several --mostly minor-- modifications to the lesson.
=> SQL lesson fixes

sql.md
- challenge uses rodent, which is not possible to do at this stage of the
lesson as JOIN hasn't been covered yet
- missed one of the exercises when converting to challenge formatting
- last query still used older column names
=> a few fixes after teaching the lesson

CONTRIBUTING.md
1. We are now using gh-pages as the main branch
2. Update example branch names and format to reflect that is just an SQL repo
=> Update CONTRIBUTING to reflect new structure

sql.md
This serves as a good foundation for more advanced SQL material and
aliases are very common in SQL so having been exposed to them will
help students understand material they will encounter online.
This material brought to you by the suggestion of @lwasser and @emhart.
Fixes #22.
=> Add introduction to aliases

CONTRIBUTING.md
Based on the decision in https://github.com/datacarpentry/planning/issues/13
=> Add guidelines for contributing data

index.md
Added @ethanwhite tips on how to zoom in on the SQLite. It's always and issue and adding it to the index would really be helpful (increases the chances the instructors will actually read this!)
=> Instructions how to zoom in on SQLite

01-sql-basic-queries.md, 02-sql-aggregation.md
* remove trailing white spaces
* fix formatting in challenge
* fix typo
=> Minor fixes

03-sql-joins-aliases.md
This is one of the two common approaches to join style. e.g.,:
http://www.sql-tutorial.com/sql-join-sql-tutorial/
And students in class have indicated that this is easier to understand.
Closes #38.
=> Change JOIN stucture to include FROM and JOIN on same line

01-sql-basic-queries.md, 02-sql-aggregation.md, 03-sql-joins-aliases.md, sql-solutions.md, sql_cheat_sheet.md
Added markdown flags to indicate code blocks contain SQL, ie eligible for SQL syntax highlighting.
=> Add sql syntax highlight

01-sql-basic-queries.md, 02-sql-aggregation.md, 03-sql-joins-aliases.md, sql-solutions.md, sql_cheat_sheet.md
Reverts datacarpentry/sql-ecology#58
The removal of empty lines renders fine on github itself, but doesn't render properly on github pages, so this broken the layout of the current lesson.
=> Revert "Add sql syntax highlight"

03-sql-joins-aliases.md
There is a typo in the query. surv.genus needs to be sp.genus
=> update typo in the query

03-sql-joins-aliases.md
Adding exercise for instructor training. It checks that the learner understand query that combine data as well as filter and calculate average that covered previous lessons.
=> Add exercise for the instructor training

03-sql-joins-aliases.md
When we ran this lesson, we had a bit of spare time towards the end of the lesson, so we set the learners a number of *challenges* to explore the data a bit further. This worked quite well to keep learners engaged, and to have a feel of how they could use SQL to answer questions on their own.
=> Additional SQL challenge

03-sql-joins-aliases.md
As discussed in PR #67 , the key word `USING` is introduced in the lesson.
I've decided to introduce `USING` first, and then `ON` as an alternative when column names do not match. This seems more logical to me, but it could also be the other way around. What do you think @ethanwhite @waveform80 ?
=> Introduced 'USING'

03-sql-joins-aliases.md
While running the workshop at Utrecht, noticed that the challenges do not appear as a list on the HTML. Also, having solutions at hand may be useful.
=> Extra challenges

01-sql-basic-queries.md
As per #55 -- added a note on comments.
Also added some github markdown syntax to highlight the keywords and such in *some* blocks. Happy to do for all.
=> Comments in SQL

01-sql-basic-queries.md, 02-sql-aggregation.md
I'm opening this PR so that we can track and discuss the progress on adding information about views.
- ~~update data through a view~~
=> Views in 02

00-sql-introduction.md, 01-sql-basic-queries.md, 03-sql-joins-aliases.md
And a bit of code cleanup -- notably, all code blocks have a single clause/line.
=> Markdown formatting

01-sql-basic-queries.md, 02-sql-aggregation.md
As suggested in #53 -- a short paragraph on `HAVING` in lesson 2.
Comments / feedback welcome.
No challenge yet.
=> Add discussion of HAVING

01-sql-basic-queries.md, 02-sql-aggregation.md, 03-sql-joins-aliases.md
Made the semicolon use consistent, corrected one mistake in aggregation, changed one-liner in basics to multi-line to be consistent.
=> Some consistency changes, one mistake correction.

03-sql-joins-aliases.md
Adding details of how rows/colums are processed when joining tables.
Tables will help visualize the join.
=> Explain joins using table columns/rows

00-sql-introduction.md
When I taught the SQL lesson this week, I re-ordered the intro material a bit as follows.  
* added a section at the beginning where learners look at the data in spreadsheets
* have students open and look at a database before creating their own
The questions I added at the beginning are such that you could answer them after the first two sections of the lesson, which could be a nice callback.  
This PR is primarily meant for discussion: if people like the re-ordering, feel free to merge, otherwise, let me know what other, less drastic changes would be better and I'll re-submit.  :)
=> re-ordering the introduction to SQL

03-sql-joins-aliases.md
I was just going through the lessons prepping to teach and found 3 places where the semicolans were missing.
=> adding in three missing ;

03-sql-joins-aliases.md
gender != sex and I have changed both references of gender to sex. This will make the lesson easier to read, since the column is called sex in the surveys sheet and its accurate.  
As far as I am aware we are not able to determine the gender of animals, but we can figure out their sex, most of the time
=> gender != sex

01-sql-basic-queries.md
PR from https://github.com/datacarpentry/sql-ecology-lesson/issues/96 to provide clarification about the use of 'species' table and column name.
=> added clarification about species table

02-sql-aggregation.md
This should have significant review before merging!  It's mostly random stuff that I used in my latest workshop.  
Touches on #78
=> adding null value stuff

instructor-notes.md
I'm adding to the instructor's notes, mainly: 
* motivation and some sample intro slides
* a way I've written queries up on the board
* an interactive activity I've done
=> Adding activities

02-sql-aggregation.md
=> Fix code formatting in 02-sql-aggregation.md

01-sql-basic-queries.md, 02-sql-aggregation.md
Minor changes to make the lessons more understandable. Added wording to denote where queries should be written (not immediately obvious). Also removed the table.colname formatting from early in the series, as this is not introduced until the next part of the lesson. It's use before introduction potentially creates confusion. I feel these changes just make everything a bit more understandable to a user unfamiliar with SQL.
=> Readability changes

00-sql-introduction.md
The first research question in the first challenge wasn't very focused. I think this one gives the learner a clearer picture of how they would go about answering that research question manually, which can then be contrasted more clearly with an approach using a database. 
I also made the bullet point items under "why use relational databases" full sentences.
=> clarify challenge, full sentences

00-sql-introduction.md
This pull request is an exercise to fullfill the Software/Data Carpentry instructor training held in May, 2016 in Edinburgh
=> github pull request exercise

01-sql-basic-queries.md
@orchid00 @tpoisot 
Data Carpentry is the process of developing our surveys so that we can have a better understanding of our learners' skills and self-efficacy after taking a Data Carpentry workshop. To do this we want to improve the learning objectives for all of our lessons so that they are measurable. I added the learning objectives I developed with Erin's help for the SQL lesson. I would like to have your feedback and input as maintainers of the SQL lesson by December 28th. I appreciate your help and support.
=> Added learning objectives

00-sql-introduction.md
@tpoisot @orchid00 
Data Carpentry is the process of developing our surveys so that we can have a better understanding of our learners' skills and self-efficacy after taking a Data Carpentry workshop. To do this we want to improve the learning objectives for all of our lessons so that they are measurable. I added the learning objectives I developed with Erin's help for the SQL lesson. I would like to have your feedback and input as maintainers of the SQL lesson by December 28th. I appreciate your help and support.
=> Added learning objectives to

00-sql-introduction.md, 01-sql-basic-queries.md, 02-sql-aggregation.md, sql-solutions.md
Contribution for software carpentry instructor qualification to address the issues raised in
https://github.com/datacarpentry/sql-ecology-lesson/issues/49. Added a table with suggested data types during the import step. Minor change in some queries to take advantage of the suggested data types. Added explanations of changes required to queries if different data types were used
=> Fanie.riekert data types

_includes/sqlSetup.html
=> Add detailed instructions to sqlSetup.html

.github/ISSUE_TEMPLATE.md
Thank you for your pull request!
These lessons are being prepared for publication and are therefore frozen
to significant changes in preparation for their release. If you
are submitting a PR, please make sure it's related to a filed issue.
@tracykteal or @tpoisot can you merge this to help us crosslink issues to our running checklist?
=> Link to #124

_episodes/00-sql-introduction.md
Thank you for your pull request!
These lessons are being prepared for publication and are therefore frozen
to significant changes in preparation for their release. If you
are submitting a PR, please make sure it's related to a filed issue.
=> Small fixes to spelling, bolding, and wording

_episodes/00-sql-introduction.md
if this works, it will close #130 (or it would if that issue hadn't been closed
before being fixed). it attempts to refer to the correct url suggested there.
if it doesn't work, hopefully @tracykteal / @ErinBecker can follow up and patch
(per discussion in #144)
=> Fixes, hopefully, setup link in episode 00

_episodes/02-sql-aggregation.md
1.  Add short explanation at end of what happens when some values are aggregated and some are not.
1.  Clean up long lines and trailing whitespace.
1.  Clean up inconsistent I/we usage.
1.  Format column names and keywords as code.
Closes #52.
=> Warn about what happens when aggregation function not specified.

_episodes/02-sql-aggregation.md
Thank you for your pull request!
These lessons are being prepared for publication and are therefore frozen
to significant changes in preparation for their release. If you
are submitting a PR, please make sure it's related to a filed issue.
references issue https://github.com/datacarpentry/sql-ecology-lesson/issues/144
=> add closing semicolons to select statements

_episodes/03-sql-joins-aliases.md
Thank you for your pull request!
These lessons are being prepared for publication and are therefore frozen
to significant changes in preparation for their release. If you
are submitting a PR, please make sure it's related to a filed issue.
refernces issue https://github.com/datacarpentry/sql-ecology-lesson/issues/143
=> add closing semicolons

_episodes/00-sql-introduction.md
The other two tables are still imported as a challenge later (closes #136).
Also add formatting to table names in this section and the challenge
=> Adapt import walk-through to explicitly import surveys.csv

_episodes/00-sql-introduction.md
This PR attempts to clarify the initial definition of a relational database.
We should add a diagram showing the structure of the example database, but
1.  This should be done where that database is introduced.
1.  I believe the diagram provided by @njamescouk (see <https://github.com/datacarpentry/sql-ecology-lesson/issues/140#issuecomment-288047797>) will confuse learners, since its rows and columns do not correspond to records and fields. We should instead create a diagram that shows column headers (field names) and the first few rows of each table with arrows linking foreign keys to primary keys.
Closes #140.
=> Clarifying definition of what a database is.

_episodes/00-sql-introduction.md
Added three key points which approximately summarize the material.
I chose not to include particular sequences of operations within the GUI.
This PR deals with one component of #129.
I'd appreciate feedback on my choice of key points.
=> Add key points to the introduction episode.

CONTRIBUTING.md
closes #127 (also fixes small typo)
=> Fix FIXMEs in CONTRIBUTING

_episodes/01-sql-basic-queries.md
Tried to add relevant points without repeating what was in the episode too much. Key points subject to feedback and change. This is part of issue #129 Format Key Points.
=> Added key point section to episode Basic Queries

_episodes/02-sql-aggregation.md
Summarized some of the important functions, keywords, and concepts.
References #129 
Feedback appreciated on choice of key points.
=> Add key-points to the aggregation episode.

_episodes/03-sql-joins-aliases.md
=> Add key points to 03 (re #129)

_episodes/00-sql-introduction.md
Addresses https://github.com/datacarpentry/sql-ecology-lesson/issues/167
Also did updates for the other data types to match those if the sqlite database is directly imported.
=> updated table with data types matching the sqlite database

_episodes/00-sql-introduction.md
When creating a new database, the tool displays a file explorer window.
It is confusing if not well stated that you do not have to select a file.
The only step needed should be clicking open.
=> Add Clear discription of creating a database.

_episodes/00-sql-introduction.md
Adding references to Oracle and Microsoft solutions for creating relational databases since some institutions might have access to these products. Included are some minor edits.
=> Added Oracle and Microsoft solutions for RDBMS.

_episodes/02-sql-aggregation.md
As the exercise is currently, the decimal function is basically hidden, until you force the equation to have decimal places, which then shows being limited to 3.
=> Update on lines 36 and 38

_episodes/03-sql-joins.md
@orchid00 @tpoisot there was a [learning objective](https://docs.google.com/document/d/1pBPIorIQUEK59yoxppSHuHHURc3NZvLWgfoixIj3YUI/edit) missing.
=> Added missing learning objective

_episodes/00-sql-introduction.md
Revised learning objectives that were approved in [this document](https://docs.google.com/document/d/1pBPIorIQUEK59yoxppSHuHHURc3NZvLWgfoixIj3YUI/edit). @orchid00 @tpoisot
=> Revised learning objectives

_episodes/00-sql-introduction.md, _extras/guide.md, index.md, setup.md
Initial take at updating the lesson after SQLite Manager no longer works on Firefox.
Fixes #199
=> Use DB Browser for SQLite instead of Firefox

_episodes/02-sql-aggregation.md
=> Reword a challenge in COUNT and GROUP BY

_extras/about.md, _extras/discuss.md, _extras/guide.md
https://github.com/carpentries/instructor-training/issues/781#issuecomment-432722313
=> Remove permalinks

CONTRIBUTORS.md, _extras/guide.md, setup.md
See diff & https://www.doi.org/doi_handbook/3_Resolution.html#3.8
=> Update old DOI-URLs (duplicated)

_episodes/02-sql-aggregation.md
=> Fix typo: AVERAGE -> AVG

_episodes/02-sql-aggregation.md
=> Fix number of records in AVG() example

_episodes/01-sql-basic-queries.md
Added a comma to sentence in line 118. Sentences starting with "if"-clause should be followed by a comma.
Started a new paragraph after line 118 to make it clearer that we are moving to the next point.
=> Changes to make text more readable

_episodes/00-sql-introduction.md
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
=> Correct link to the setup page

_episodes/02-sql-aggregation.md
I've taught this and found people didn't find it so 'simple.'
=> remove 'simply' from language

_extras/guide.md
Cleaned up formatting of proposed whiteboard queries. Fleshed out section on Interactive Database. For Carpentry Instructor training checkout.
=> Updated instructor hints for SQL Ecology lesson

_episodes/03-sql-joins.md
Responded to issue #271 by first, editing optional challenge #2 to add a subquestion about the number of unsexed individuals per year, and modifying the solution to remove the "where sex is not null" statement (so that learners can see an example of what it looks like when one of the grouping variables is NULL); and second, editing optional challenge #3 to make explicit the desire to exclude NULL values.
=> Rewording of optionnal challenges (03-sql-joins) #271 (checkout)

_episodes/00-sql-introduction.md, _episodes/01-sql-basic-queries.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> removed unnecessary uses of word "just"

_episodes/03-sql-joins.md
Small change to final challenge to match number of solution to number of question in the challenge.
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your …
=> Numbering for solutions doesn't match

README.md
Closes #290 
Wait to merge until we hear from Donal.
=> adding Katy and Christina as maintainers

_episodes/00-sql-introduction.md
=> amending incorrect statement about database manager variation

_episodes/02-sql-aggregation.md
=> removing outdated alternate instructions for creating views

_episodes/00-sql-introduction.md, _episodes/01-sql-basic-queries.md, _episodes/02-sql-aggregation.md, _episodes/03-sql-joins.md
Previous names were inconsistent in grammatical structure and capitalization. 
Here I'm going for "Verb + How".  (so, "Combining data with joins" instead of "Joins".)
=> making episode names more consistent and descriptive

index.md
Changes to the Prerequisite part of the Getting Start box  related to issue #263 (Text clarification in lesson Home #263)
=> Changes to the Prerequisite in Getting Start box

_episodes/00-sql-introduction.md
Clarification was requested in the 'Questions' section not to repeat download instructions already in the 'Setup' section.
=> Clarification to Questions section

_episodes/01-sql-basic-queries.md, _episodes/02-sql-aggregation.md, _episodes/03-sql-joins.md
I am proposing to change the term "command" with "clause" as they are used interchangeably throughout the episodes  2, 3 and 4 of the lesson. I believe that only one term (preferably "clause") must be used to avoid any confusion to the readers. 
Because SQL comes from the field of Computer science, I believe that use of "clause" is more appropriate in this context. I strongly feel that the above occurrences of "command" must be changed with "clause" to maintain consistency in the lesson.
=> Replacing COMMAND with CLAUSE

_episodes/00-sql-introduction.md, _episodes/02-sql-aggregation.md, _episodes/03-sql-joins.md
Hi Team,
I have processed the spelling corrections I identified in [this issue](https://github.com/datacarpentry/sql-ecology-lesson/issues/348#issue-1577229359). This is my first community contribution, so hopefully I've followed the process correctly.
Thanks
=> Spelling corrections for checkout

reference.md
=> Adding description + examples from some keywords

_episodes/01-sql-basic-queries.md
#266 
Improved the basic introduction to SQL code at the beginning of the "## Writing my first query" section.
-Explained semicolon in a callout box.
-Moved explanation regarding line breaks from bottom of page to the callout box earlier in the page.
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we …
=> Update 01-sql-basic-queries.md (Issue #266)

AUTHORS, _episodes/00-sql-introduction.md, _episodes/01-sql-basic-queries.md
Formatting fixes:
- Add a proper callout box for information on multiple statements.
- Reorder instruction list so last statement appears with others, and so the numbering doesn't reset.
- Add myself to authors (from prior work).
=> Add callout, fix numbered list, add to authors.

index.md, learners/setup.md
See commit messages for more details.
=> Adapt setup section and references to it to workbench

README.md, learners/reference.md
Resolves #355. @jd-foster, I'd be curious to hear your thoughts on this. Some of the definitions feel a little technical. I think that's probably okay because they're not part of the main lesson flow but I could be convinced otherwise.
=> Updated maintainer list and glossary (#355)

learners/setup.md
=> updating language for checking installation

learners/reference.md, learners/sql-cheat-sheet.md
=> Move cheat sheet for updated workbench
